export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const SET_DATABASE_REQUESTED = 'SET_DATABASE_REQUESTED';
export const SET_DATABASE_FULFILLED = 'SET_DATABASE_FULFILLED';
export const SET_DATABASE_REJECTED = 'SET_DATABASE_REJECTED';
export const REPLACE_CONFIG = 'REPLACE_CONFIG';
