export const INITIALIZE_DATABASE_REQUEST = 'INITIALIZE_DATABASE_REQUEST';
export const INITIALIZE_DATABASE_SUCCESS = 'INITIALIZE_DATABASE_SUCCESS';
export const INITIALIZE_DATABASE_FAILURE = 'INITIALIZE_DATABASE_FAILURE';

export const CLEAR_STATE = 'CLEAR_STATE';
export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
export const RESET_GLOBAL_STATUS = 'RESET_GLOBAL_STATUS';

export const LOAD_COUNTRIES_REQUEST = 'LOAD_COUNTRIES_REQUEST';
export const LOAD_COUNTRIES_FAILURE = 'LOAD_COUNTRIES_FAILURE';
export const LOAD_COUNTRIES_SUCCESS = 'LOAD_COUNTRIES_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const LOAD_REGISTRATION_SUCCESS = 'LOAD_REGISTRATION_SUCCESS';
export const LOAD_REGISTRATION_FAILURE = 'LOAD_REGISTRATION_FAILURE';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const PASSWORD_RESET_LINK_DELIVERY_SUCCESS = 'PASSWORD_RESET_LINK_DELIVERY_SUCCESS';
export const PASSWORD_RESET_LINK_DELIVERY_FAILURE = 'PASSWORD_RESET_LINK_DELIVERY_FAILURE';

export const REGISTER_BUSINESS_REQUEST = 'REGISTER_BUSINESS_REQUEST';
export const REGISTER_BUSINESS_SUCCESS = 'REGISTER_BUSINESS_SUCCESS';
